apiVersion: v1
kind: Template
labels:
  app: mongoexporter
  template: mongoexporter-buildconfig-with-secret
metadata:
  annotations:
    description: MongoDB Exporter - BuildConfig with Secret
      see https://github.com/Worteks/docker-mongoexporter
    iconClass: icon-mongodb
    openshift.io/display-name: MongoDB Exporter
    tags: exporter,prometheus,mongodb
  name: mongodb-buildconfig-with-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-username: "{.data['username']}"
    name: git-${FRONTNAME}-${MONGO_EXPORTER_REPOSITORY_REF}
  stringData:
    username: "${GIT_DEPLOYMENT_TOKEN}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds MongoDB Exporter images
    labels:
      name: mongoexporter-${FRONTNAME}-${MONGO_EXPORTER_REPOSITORY_REF}
    name: mongoexporter-${FRONTNAME}-${MONGO_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: /
      git:
        uri: ${MONGO_EXPORTER_REPOSITORY_URL}
        ref: "${MONGO_EXPORTER_REPOSITORY_REF}"
      sourceSecret:
        name: git-${FRONTNAME}-${MONGO_EXPORTER_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: mongoexporter-${FRONTNAME}:${MONGO_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: GIT_DEPLOYMENT_TOKEN
  description: Git deployment token
  displayName: Git Deployment Token
  required: true
- name: MONGO_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: MONGO_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your MongoDB exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-mongoexporter.git
