apiVersion: v1
kind: Template
labels:
  app: mongoexporter
  template: mongoexporter-imagestream
metadata:
  annotations:
    description: MongoDB Exporter - ImageStream
      see https://github.com/Worteks/docker-mongoexporter
    iconClass: icon-mongodb
    openshift.io/display-name: MongoDB Exporter
    tags: exporter,prometheus,mongodb
  name: mongoexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in MongoDB Exporter image
    name: mongoexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
