apiVersion: v1
kind: Template
labels:
  app: mongoexporter
  template: mongoexporter-secret
metadata:
  annotations:
    description: MongoDB Exporter - Secret
      see https://github.com/Worteks/docker-mongoexporter
    iconClass: icon-mongodb
    openshift.io/display-name: MongoDB Exporter
    tags: exporter,prometheus,mongodb
  name: mongoexporter-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-admin_password: "{.data['database-admin-password']}"
      template.openshift.io/expose-database_name: "{.data['database-name']}"
      template.openshift.io/expose-password: "{.data['database-password']}"
      template.openshift.io/expose-username: "{.data['database-user']}"
    name: mongodb-${FRONTNAME}
  stringData:
    database-admin-password: ${MONGODB_ADMIN_PASSWORD}
    database-name: ${MONGODB_DATABASE}
    database-password: ${MONGODB_PASSWORD}
    database-user: ${MONGODB_USER}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: MONGODB_ADMIN_PASSWORD
  description: Password for the database admin user.
  displayName: MongoDB Admin Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
- name: MONGODB_DATABASE
  description: Name of the MongoDB database accessed.
  displayName: MongoDB Database Name
  required: true
  value: sampledb
- name: MONGODB_PASSWORD
  description: Password for the MongoDB connection user.
  displayName: MongoDB Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
- name: MONGODB_USER
  description: Username for MongoDB user that will be used for accessing the database.
  displayName: MongoDB Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  required: true
